name: custom_shimmer_loader_state_mixin_flutter_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  skeletons: ^0.0.3
  cached_network_image: ^3.0.0
  internet_connection_checker: ^0.0.1+2
  lottie: ^1.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - lottie/

